version: '3'
services:
    tjth-cv:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - 8001:8001
        container_name: tjth-cv
        command: ['node','app.js']